backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "svPosts"
    label: "Swedish Posts"
    folder: "src/pages/sv/aktuellt"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "post"}
      - {label: "Language", name: "language", widget: "hidden", default: "sv"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: 'Featured image', name: featuredImage, widget: image, required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "enPosts"
    label: "English Posts"
    folder: "src/pages/en/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false    
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "post"}
      - {label: "Language", name: "language", widget: "hidden", default: "en"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: 'Featured image', name: featuredImage, widget: image, required: false}      
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "frPosts"
    label: "French Posts"
    folder: "src/pages/fr/actualite"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false    
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "post"}
      - {label: "Language", name: "language", widget: "hidden", default: "fr"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: 'Featured image', name: featuredImage, widget: image, required: false}
      - {label: "Body", name: "body", widget: "markdown"}      
  - name: 'svPages'
    label: 'Swedish Pages'
    delete: false 
    editor:
      preview: false    
    files:
      - file: 'src/pages/index.md'
        label: 'Index'
        name: 'index'
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: 'Background image', name: bgImage, widget: image, required: false}
          - {label: "Body", name: "body", widget: "markdown"}            
      - file: 'src/pages/sv/om-oss.md'
        label: 'Om oss'
        name: 'om-oss'
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: 'Background image', name: bgImage, widget: image, required: false}
          - {label: "Ingress", name: "ingress", widget: "markdown", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: 'src/pages/sv/bidrag.md'
        label: 'Bidrag'
        name: 'bidrag'
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: 'Background image', name: bgImage, widget: image, required: false}
          - {label: "Ingress", name: "ingress", widget: "markdown", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: 'src/pages/sv/volontar.md'
        label: 'Volontär'
        name: 'volontar'
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: 'Background image', name: bgImage, widget: image, required: false}
          - {label: "Ingress", name: "ingress", widget: "markdown", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: 'src/pages/sv/om-senegal.md'
        label: 'Om Senegal'
        name: 'om-senegal'
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: 'Background image', name: bgImage, widget: image, required: false}
          - {label: "Ingress", name: "ingress", widget: "markdown", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: 'src/pages/sv/kontakt.md'
        label: 'Kontakt'
        name: 'kontakt'
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: 'Background image', name: bgImage, widget: image, required: false}
          - {label: "Ingress", name: "ingress", widget: "markdown", required: false}
          - {label: "Body", name: "body", widget: "markdown"}                    
  - name: 'enPages'
    label: 'English Pages'
    delete: false 
    editor:
      preview: false    
    files:
      - file: 'src/pages/en/index.md'
        label: 'Index'
        name: 'index'
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: 'Background image', name: bgImage, widget: image, required: false}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: 'src/pages/en/about-us.md'
        label: 'About us'
        name: 'about-us'
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: 'Background image', name: bgImage, widget: image, required: false}
          - {label: "Ingress", name: "ingress", widget: "markdown", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: 'src/pages/en/contribution.md'
        label: 'Contribution'
        name: 'contribution'
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: 'Background image', name: bgImage, widget: image, required: false}
          - {label: "Ingress", name: "ingress", widget: "markdown", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: 'src/pages/en/volunteer.md'
        label: 'Volunteer'
        name: 'volunteer'
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: 'Background image', name: bgImage, widget: image, required: false}
          - {label: "Ingress", name: "ingress", widget: "markdown", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: 'src/pages/en/about-senegal.md'
        label: 'About Sénégal'
        name: 'about-senegal'
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: 'Background image', name: bgImage, widget: image, required: false}
          - {label: "Ingress", name: "ingress", widget: "markdown", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: 'src/pages/en/contact.md'
        label: 'Contact'
        name: 'contact'
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: 'Background image', name: bgImage, widget: image, required: false}
          - {label: "Ingress", name: "ingress", widget: "markdown", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
  - name: 'frPages'
    label: 'French Pages'
    delete: false 
    editor:
      preview: false    
    files:
      - file: 'src/pages/fr/index.md'
        label: 'Index'
        name: 'index'
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: 'Background image', name: bgImage, widget: image, required: false}
          - {label: "Body", name: "body", widget: "markdown"}      
      - file: 'src/pages/fr/a-propos-de-nous.md'
        label: 'à Propos de nous'
        name: 'a-propos-de-nous'
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: 'Background image', name: bgImage, widget: image, required: false}
          - {label: "Ingress", name: "ingress", widget: "markdown", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: 'src/pages/fr/contribution.md'
        label: 'Contribution'
        name: 'contribution'
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: 'Background image', name: bgImage, widget: image, required: false}
          - {label: "Ingress", name: "ingress", widget: "markdown", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: 'src/pages/fr/volontaire.md'
        label: 'Volontaire'
        name: 'volontaire'
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: 'Background image', name: bgImage, widget: image, required: false}
          - {label: "Ingress", name: "ingress", widget: "markdown", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: 'src/pages/fr/de-senegal.md'
        label: 'de Sénégal'
        name: 'de-senegal'
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: 'Background image', name: bgImage, widget: image, required: false}
          - {label: "Ingress", name: "ingress", widget: "markdown", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: 'src/pages/fr/contact.md'
        label: 'Contact'
        name: 'contact'
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: 'Background image', name: bgImage, widget: image, required: false}
          - {label: "Ingress", name: "ingress", widget: "markdown", required: false}
          - {label: "Body", name: "body", widget: "markdown"}                 